using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HRI.Models
{
    public static class PlansDescriptioData
    {
        public static PlanDescription PrimarySelectPlatinumPlanDescription = new PlanDescription()
        {
            Deductible = "$0",
            Coinsurance = "20%",
            OutofPocketMaximum = "$1400",
            PreventiveServices = "$0",
            OfficeVisit = "$0",
            OutpatientSurgicalProcedures = "20% Cost Sharing",
            EmergencyRoom = "$250 Copay after Deductible",
            Ambulance = "$100 Copay",
            UrgentCareCenter = "$100 Copay",
            InpatientHospital = "20% Cost Sharing",
            OutpatientSurgicalProceduresFacility = "20% Cost Sharing",
            SkilledNursingFacility = "20% Cost Sharing",
            LaboratoryTesting = "$75 Copay",
            EKG = "$75 Copay",
            RoutineRadiology = "$75 Copay",
            AdvancedRadiology = "$75 Copay",
            InpatientMaternity = "20% Cost Sharing",
            InpatientMentalHealth = "20% Cost Sharing",
            OutpatientMentalHealth = "$0 Copay",
            InpatientSubstanceAbuseRehab = "20% Cost Sharing",
            InpatientSubstanceAbuseDetox = "20% Cost Sharing",
            OutpatientSubstanceAbuse = "$0 Copay",
            InsulinandOtherOralAgents = "$0 Copay",
            DiabeticMedicalSupplies = "$0 Copay",
            ChiropracticServices = "$75 Copay",
            PhysicalOccupationalSpeechTherapies = "$30 Copay",
            CardiacRehabilitation = "$30 Copay",
            PulmonaryRehabilitation = "$30 Copay",
            DurableMedicalEquipment = "20% Cost Sharing",
            ProstheticsandAppliances = "20% Cost Sharing",
            Chemotherapy = "$15 Copay",
            HomeHealthCare = "$15 Copay",
            PrescriptionPlan = "$0/$35 after Deductible /$70 after Deductible",
            MaintenanceMedications = "$0/$35 after Deductible /$70 after Deductible",
            MedicalExam = "$15 Copay",
            StandardPlasticLenses = "20% Cost Sharing",
            Frames = "20% Cost Sharing",
            ConventionalContactLenses = "20% Cost Sharing"

        };

        public static PlanDescription PrimarySelectGoldPlanDescription = new PlanDescription()
        {
            Deductible = "$250",
            Coinsurance = "20%",
            OutofPocketMaximum = "$3500",
            PreventiveServices = "$0",
            OfficeVisit = "$0",
            OutpatientSurgicalProcedures = "20% Cost Sharing",
            EmergencyRoom = "$250 Copay after Deductible",
            Ambulance = "$150 Copay",
            UrgentCareCenter = "$100 Copay",
            InpatientHospital = "20% Cost Sharing",
            OutpatientSurgicalProceduresFacility = "20% Cost Sharing",
            SkilledNursingFacility = "20% Cost Sharing",
            LaboratoryTesting = "$75 Copay",
            EKG = "$75 Copay",
            RoutineRadiology = "$75 Copay",
            AdvancedRadiology = "$75 Copay",
            InpatientMaternity = "20% Cost Sharing",
            InpatientMentalHealth = "20% Cost Sharing",
            OutpatientMentalHealth = "$0 Copay",
            InpatientSubstanceAbuseRehab = "20% Cost Sharing",
            InpatientSubstanceAbuseDetox = "20% Cost Sharing",
            OutpatientSubstanceAbuse = "$0 Copay",
            InsulinandOtherOralAgents = "$0 Copay",
            DiabeticMedicalSupplies = "$0 Copay",
            ChiropracticServices = "$75 Copay",
            PhysicalOccupationalSpeechTherapies = "$30 Copay",
            CardiacRehabilitation = "$30 Copay",
            PulmonaryRehabilitation = "$30 Copay",
            DurableMedicalEquipment = "20% Cost Sharing",
            ProstheticsandAppliances = "20% Cost Sharing",
            Chemotherapy = "$25 Copay",
            HomeHealthCare = "$25 Copay",
            PrescriptionPlan = "$0/$35 after Deductible /$70 after Deductible",
            MaintenanceMedications = "$0/$35 after Deductible /$70 after Deductible",
            MedicalExam = "$25 Copay",
            StandardPlasticLenses = "20% Cost Sharing",
            Frames = "20% Cost Sharing",
            ConventionalContactLenses = "20% Cost Sharing"

        };

        public static PlanDescription PrimarySelectSilverPlanDescription = new PlanDescription()
        {
            Deductible = "$2000",
            Coinsurance = "20%",
            OutofPocketMaximum = "$6350",
            PreventiveServices = "$0",
            OfficeVisit = "$0",
            OutpatientSurgicalProcedures = "20% Cost Sharing",
            EmergencyRoom = "$250 Copay after Deductible",
            Ambulance = "$150 Copay",
            UrgentCareCenter = "$100 Copay",
            InpatientHospital = "20% Cost Sharing",
            OutpatientSurgicalProceduresFacility = "20% Cost Sharing",
            SkilledNursingFacility = "20% Cost Sharing",
            LaboratoryTesting = "$75 Copay",
            EKG = "$75 Copay",
            RoutineRadiology = "$75 Copay",
            AdvancedRadiology = "$75 Copay",
            InpatientMaternity = "20% Cost Sharing",
            InpatientMentalHealth = "20% Cost Sharing",
            OutpatientMentalHealth = "$0 Copay",
            InpatientSubstanceAbuseRehab = "20% Cost Sharing",
            InpatientSubstanceAbuseDetox = "20% Cost Sharing",
            OutpatientSubstanceAbuse = "$0 Copay",
            InsulinandOtherOralAgents = "$0 Copay",
            DiabeticMedicalSupplies = "$0 Copay",
            ChiropracticServices = "$75 Copay",
            PhysicalOccupationalSpeechTherapies = "$30 Copay",
            CardiacRehabilitation = "$30 Copay",
            PulmonaryRehabilitation = "$30 Copay",
            DurableMedicalEquipment = "20% Cost Sharing",
            ProstheticsandAppliances = "20% Cost Sharing",
            Chemotherapy = "$30 Copay",
            HomeHealthCare = "$30 Copay",
            PrescriptionPlan = "$0/$35 after Deductible /$70 after Deductible",
            MaintenanceMedications = "$0/$35 after Deductible /$70 after Deductible",
            MedicalExam = "$30 Copay",
            StandardPlasticLenses = "20% Cost Sharing",
            Frames = "20% Cost Sharing",
            ConventionalContactLenses = "20% Cost Sharing"
        };

        public static PlanDescription PrimarySelectBronzePlanDescription = new PlanDescription()
        {
            Deductible = "$6350",
            Coinsurance = "20%",
            OutofPocketMaximum = "$6350",
            PreventiveServices = "$0",
            OfficeVisit = "$0",
            OutpatientSurgicalProcedures = "Subject To Deductible",
            EmergencyRoom = "Subject To Deductible",
            Ambulance = "Subject To Deductible",
            UrgentCareCenter = "Subject To Deductible",
            InpatientHospital = "Subject To Deductible",
            OutpatientSurgicalProceduresFacility = "Subject To Deductible",
            SkilledNursingFacility = "Subject To Deductible",
            LaboratoryTesting = "Subject To Deductible",
            EKG = "Subject To Deductible",
            RoutineRadiology = "Subject To Deductible",
            AdvancedRadiology = "Subject To Deductible",
            InpatientMaternity = "Subject To Deductible",
            InpatientMentalHealth = "Subject To Deductible",
            OutpatientMentalHealth = "$0 Copay",
            InpatientSubstanceAbuseRehab = "Subject To Deductible",
            InpatientSubstanceAbuseDetox = "Subject To Deductible",
            OutpatientSubstanceAbuse = "$0 Copay",
            InsulinandOtherOralAgents = "$0 Copay",
            DiabeticMedicalSupplies = "$0 Copay",
            ChiropracticServices = "Subject To Deductible",
            PhysicalOccupationalSpeechTherapies = "Subject To Deductible",
            CardiacRehabilitation = "Subject To Deductible",
            PulmonaryRehabilitation = "Subject To Deductible",
            DurableMedicalEquipment = "Subject To Deductible",
            ProstheticsandAppliances = "Subject To Deductible",
            Chemotherapy = "Subject To Deductible",
            HomeHealthCare = "Subject To Deductible",
            PrescriptionPlan = "$0/Subject To Deductible/Subject To Deductible",
            MaintenanceMedications = "$0/Subject To Deductible/Subject To Deductible",
            MedicalExam = "Subject To Deductible",
            StandardPlasticLenses = "Subject To Deductible",
            Frames = "Subject To Deductible",
            ConventionalContactLenses = "Subject To Deductible"
        };

        public static PlanDescription PrimarySelectSilverEPOPlanDescription = new PlanDescription()
        {
            Deductible = "$2000",
            Coinsurance = "20%",
            OutofPocketMaximum = "$6350",
            PreventiveServices = "$0",
            OfficeVisit = "$0 Copay if using selected Doctor",
            OutpatientSurgicalProcedures = "20% Cost Sharing after Deductible",
            EmergencyRoom = "$250 Copay after Deductible",
            Ambulance = "$150 Copay after Deductible",
            UrgentCareCenter = "$100 Copay after Deductible",
            InpatientHospital = "20% Cost Sharing after Deductible",
            OutpatientSurgicalProceduresFacility = "20% Cost Sharing after Deductible",
            SkilledNursingFacility = "20% Cost Sharing after Deductible",
            LaboratoryTesting = "$75 Copay after Deductible",
            EKG = "$75 Copay after Deductible",
            RoutineRadiology = "$75 Copay after Deductible",
            AdvancedRadiology = "$75 Copay after Deductible",
            InpatientMaternity = "20% Cost Sharing after Deductible",
            InpatientMentalHealth = "20% Cost Sharing after Deductible",
            OutpatientMentalHealth = "$0 Copay",
            InpatientSubstanceAbuseRehab = "20% Cost Sharing after Deductible",
            InpatientSubstanceAbuseDetox = "20% Cost Sharing after Deductible",
            OutpatientSubstanceAbuse = "$0 Copay",
            InsulinandOtherOralAgents = "$0 Copay",
            DiabeticMedicalSupplies = "$0 Copay",
            ChiropracticServices = "$75 Copay",
            PhysicalOccupationalSpeechTherapies = "$30 Copay",
            CardiacRehabilitation = "$30 Copay",
            PulmonaryRehabilitation = "$30 Copay",
            DurableMedicalEquipment = "20% Cost Sharing after Deductible",
            ProstheticsandAppliances = "20% Cost Sharing after Deductible",
            Chemotherapy = "$30 Copay after Deductible",
            HomeHealthCare = "$30 Copay after Deductible",
            PrescriptionPlan = "$0/$35 after Deductible /$70 after Deductible",
            MaintenanceMedications = "$0/$35 after Deductible /$70 after Deductible",
            MedicalExam = "$30 Copay after Deductible",
            StandardPlasticLenses = "20% Cost Sharing after Deductible",
            Frames = "20% Cost Sharing after Deductible",
            ConventionalContactLenses = "20% Cost Sharing after Deductible"
        };


        public static PlanDescription EssentialCarePlatinumPlanDescription = new PlanDescription()
        {
            Deductible = "$0",
            Coinsurance = "100%",
            OutofPocketMaximum = "$2000",
            PreventiveServices = "$0",
            OfficeVisit = "$15 after deductible is met",
            OutpatientSurgicalProcedures = "$100 after deductible is met",
            EmergencyRoom = "$100 after deductible is met",
            Ambulance = "$100 after deductible is met",
            UrgentCareCenter = "$55 after deductible is met",
            InpatientHospital = "$500 after deductible is met",
            OutpatientSurgicalProceduresFacility = "$100 after deductible is met",
            SkilledNursingFacility = "$500 after deductible is met",
            LaboratoryTesting = "$35 after deductible is met",
            EKG = "$35 after deductible is met",
            RoutineRadiology = "$35 after deductible is met",
            AdvancedRadiology = "$35 after deductible is met",
            InpatientMaternity = "$500 after deductible is met",
            InpatientMentalHealth = "$500 after deductible is met",
            OutpatientMentalHealth = "$15 after deductible is met",
            InpatientSubstanceAbuseRehab = "$500 after deductible is met",
            InpatientSubstanceAbuseDetox = "$500 after deductible is met",
            OutpatientSubstanceAbuse = "$15 after deductible is met",
            InsulinandOtherOralAgents = "$15 after deductible is met",
            DiabeticMedicalSupplies = "$15 after deductible is met",
            ChiropracticServices = "$35 after deductible is met",
            PhysicalOccupationalSpeechTherapies = "$25 after deductible is met",
            CardiacRehabilitation = "$25 after deductible is met",
            PulmonaryRehabilitation = "$25 after deductible is met",
            DurableMedicalEquipment = "10% cost sharing after deductible is met",
            ProstheticsandAppliances = "10% cost sharing after deductible is met",
            Chemotherapy = "$15 after deductible is met",
            HomeHealthCare = "$15 after deductible is met",
            PrescriptionPlan = "$10/$30/$60",
            MaintenanceMedications = "$10/$30/$60",
            MedicalExam = "$15 after deductible is met",
            StandardPlasticLenses = "10% cost sharing after deductible is met",
            Frames = "10% cost sharing after deductible is met",
            ConventionalContactLenses = "10% cost sharing after deductible is met"
        };

        public static PlanDescription EssentialCareGoldPlanDescription = new PlanDescription()
        {
            Deductible = "$600",
            Coinsurance = "100%",
            OutofPocketMaximum = "$4000",
            PreventiveServices = "$0",
            OfficeVisit = "$25 after deductible is met",
            OutpatientSurgicalProcedures = "$100 after deductible is met",
            EmergencyRoom = "$150 after deductible is met",
            Ambulance = "$150 after deductible is met",
            UrgentCareCenter = "$60 after deductible is met",
            InpatientHospital = "$1000 after deductible is met",
            OutpatientSurgicalProceduresFacility = "$100 after deductible is met",
            SkilledNursingFacility = "$1000 after deductible is met",
            LaboratoryTesting = "$40 after deductible is met",
            EKG = "$40 after deductible is met",
            RoutineRadiology = "$40 after deductible is met",
            AdvancedRadiology = "$40 after deductible is met",
            InpatientMaternity = "$1000 after deductible is met",
            InpatientMentalHealth = "$25 after deductible is met",
            OutpatientMentalHealth = "$15 after deductible is met",
            InpatientSubstanceAbuseRehab = "$1000 after deductible is met",
            InpatientSubstanceAbuseDetox = "$1000 after deductible is met",
            OutpatientSubstanceAbuse = "$25 after deductible is met",
            InsulinandOtherOralAgents = "$25 after deductible is met",
            DiabeticMedicalSupplies = "$25 after deductible is met",
            ChiropracticServices = "$40 after deductible is met",
            PhysicalOccupationalSpeechTherapies = "$30 after deductible is met",
            CardiacRehabilitation = "$30 after deductible is met",
            PulmonaryRehabilitation = "$30 after deductible is met",
            DurableMedicalEquipment = "20% cost sharing after deductible is met",
            ProstheticsandAppliances = "20% cost sharing after deductible is met",
            Chemotherapy = "$25 after deductible is met",
            HomeHealthCare = "$25 after deductible is met",
            PrescriptionPlan = "$10/$35/$70",
            MaintenanceMedications = "$10/$35/$70",
            MedicalExam = "$25 after deductible is met",
            StandardPlasticLenses = "20% cost sharing after deductible is met",
            Frames = "20% cost sharing after deductible is met",
            ConventionalContactLenses = "20% cost sharing after deductible is met"
        };

        public static PlanDescription EssentialCareSilverPlanDescription = new PlanDescription()
        {
            Deductible = "$2000",
            Coinsurance = "100%",
            OutofPocketMaximum = "$5500",
            PreventiveServices = "$0",
            OfficeVisit = "$30 after deductible is met",
            OutpatientSurgicalProcedures = "$100 after deductible is met",
            EmergencyRoom = "$150 after deductible is met",
            Ambulance = "$150 after deductible is met",
            UrgentCareCenter = "$70 after deductible is met",
            InpatientHospital = "$1500 after deductible is met",
            OutpatientSurgicalProceduresFacility = "$100 after deductible is met",
            SkilledNursingFacility = "$1500 after deductible is met",
            LaboratoryTesting = "$50 after deductible is met",
            EKG = "$50 after deductible is met",
            RoutineRadiology = "$50 after deductible is met",
            AdvancedRadiology = "$50 after deductible is met",
            InpatientMaternity = "$1500 after deductible is met",
            InpatientMentalHealth = "$1500 after deductible is met",
            OutpatientMentalHealth = "$30 after deductible is met",
            InpatientSubstanceAbuseRehab = "$1500 after deductible is met",
            InpatientSubstanceAbuseDetox = "$1500 after deductible is met",
            OutpatientSubstanceAbuse = "$30 after deductible is met",
            InsulinandOtherOralAgents = "$30 after deductible is met",
            DiabeticMedicalSupplies = "$30 after deductible is met",
            ChiropracticServices = "$50 after deductible is met",
            PhysicalOccupationalSpeechTherapies = "$30 after deductible is met",
            CardiacRehabilitation = "$30 after deductible is met",
            PulmonaryRehabilitation = "$30 after deductible is met",
            DurableMedicalEquipment = "30% cost sharing after deductible is met",
            ProstheticsandAppliances = "30% cost sharing after deductible is met",
            Chemotherapy = "$30 after deductible is met",
            HomeHealthCare = "$30 after deductible is met",
            PrescriptionPlan = "$10/$35/$70",
            MaintenanceMedications = "$10/$35/$70",
            MedicalExam = "$30 after deductible is met",
            StandardPlasticLenses = "30% cost sharing after deductible is met",
            Frames = "30% cost sharing after deductible is met",
            ConventionalContactLenses = "30% cost sharing after deductible is met",
        };

        public static PlanDescription EssentialCareBronzePlanDescription = new PlanDescription()
        {
            Deductible = "$3000",
            Coinsurance = "50%",
            OutofPocketMaximum = "$6350",
            PreventiveServices = "$0",
            OfficeVisit = "50% cost sharing after deductible is met",
            OutpatientSurgicalProcedures = "50% cost sharing after deductible is met",
            EmergencyRoom = "50% cost sharing after deductible is met",
            Ambulance = "50% cost sharing after deductible is met",
            UrgentCareCenter = "50% cost sharing after deductible is met",
            InpatientHospital = "50% cost sharing after deductible is met",
            OutpatientSurgicalProceduresFacility = "50% cost sharing after deductible is met",
            SkilledNursingFacility = "50% cost sharing after deductible is met",
            LaboratoryTesting = "50% cost sharing after deductible is met",
            EKG = "50% cost sharing after deductible is met",
            RoutineRadiology = "50% cost sharing after deductible is met",
            AdvancedRadiology = "50% cost sharing after deductible is met",
            InpatientMaternity = "50% cost sharing after deductible is met",
            InpatientMentalHealth = "50% cost sharing after deductible is met",
            OutpatientMentalHealth = "50% cost sharing after deductible is met",
            InpatientSubstanceAbuseRehab = "50% cost sharing after deductible is met",
            InpatientSubstanceAbuseDetox = "50% cost sharing after deductible is met",
            OutpatientSubstanceAbuse = "50% cost sharing after deductible is met",
            InsulinandOtherOralAgents = "50% cost sharing after deductible is met",
            DiabeticMedicalSupplies = "50% cost sharing after deductible is met",
            ChiropracticServices = "50% cost sharing after deductible is met",
            PhysicalOccupationalSpeechTherapies = "50% cost sharing after deductible is met",
            CardiacRehabilitation = "50% cost sharing after deductible is met",
            PulmonaryRehabilitation = "50% cost sharing after deductible is met",
            DurableMedicalEquipment = "50% cost sharing after deductible is met",
            ProstheticsandAppliances = "50% cost sharing after deductible is met",
            Chemotherapy = "$30 after deductible is met",
            HomeHealthCare = "$30 after deductible is met",
            PrescriptionPlan = "$10/$35/$70",
            MaintenanceMedications = "$10/$35/$70",
            MedicalExam = "$10 after deductible is met",
            StandardPlasticLenses = "50% cost sharing after deductible is met",
            Frames = "50% cost sharing after deductible is met",
            ConventionalContactLenses = "50% cost sharing after deductible is met",
        };

        public static PlanDescription EssentialCareCatastrophicPlanDescription = new PlanDescription()
        {
            Deductible = "$6350",
            Coinsurance = "100%",
            OutofPocketMaximum = "$6350",
            PreventiveServices = "$0",
            OfficeVisit = "0% cost sharing after deductible is met",
            OutpatientSurgicalProcedures = "0% cost sharing after deductible is met",
            EmergencyRoom = "0% cost sharing after deductible is met",
            Ambulance = "0% cost sharing after deductible is met",
            UrgentCareCenter = "0% cost sharing after deductible is met",
            InpatientHospital = "0% cost sharing after deductible is met",
            OutpatientSurgicalProceduresFacility = "0% cost sharing after deductible is met",
            SkilledNursingFacility = "0% cost sharing after deductible is met",
            LaboratoryTesting = "0% cost sharing after deductible is met",
            EKG = "0% cost sharing after deductible is met",
            RoutineRadiology = "0% cost sharing after deductible is met",
            AdvancedRadiology = "0% cost sharing after deductible is met",
            InpatientMaternity = "0% cost sharing after deductible is met",
            InpatientMentalHealth = "0% cost sharing after deductible is met",
            OutpatientMentalHealth = "0% cost sharing after deductible is met",
            InpatientSubstanceAbuseRehab = "0% cost sharing after deductible is met",
            InpatientSubstanceAbuseDetox = "0% cost sharing after deductible is met",
            OutpatientSubstanceAbuse = "0% cost sharing after deductible is met",
            InsulinandOtherOralAgents = "0% cost sharing after deductible is met",
            DiabeticMedicalSupplies = "0% cost sharing after deductible is met",
            ChiropracticServices = "0% cost sharing after deductible is met",
            PhysicalOccupationalSpeechTherapies = "0% cost sharing after deductible is met",
            CardiacRehabilitation = "0% cost sharing after deductible is met",
            PulmonaryRehabilitation = "0% cost sharing after deductible is met",
            DurableMedicalEquipment = "0% cost sharing after deductible is met",
            ProstheticsandAppliances = "0% cost sharing after deductible is met",
            Chemotherapy = "0% cost sharing after deductible is met",
            HomeHealthCare = "0% cost sharing after deductible is met",
            PrescriptionPlan = "0% cost sharing after deductible is met",
            MaintenanceMedications = "0% cost sharing after deductible is met",
            MedicalExam = "0% cost sharing after deductible is met",
            StandardPlasticLenses = "0% cost sharing after deductible is met",
            Frames = "0% cost sharing after deductible is met",
            ConventionalContactLenses = "0% cost sharing after deductible is met",
        };
    }
}